- name: Stop systemd resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: no
    state: stopped
- name: Update apt dnsmasq
  become: yes
  apt:
    name: ["dnsmasq"]
    state: latest
- name: Template dnsmasq conf
  template:
      src: "dnsmasq.conf"
      dest: "/etc/dnsmasq.conf"
      mode: override
  notify: restart dnsmasq
  tags: deploy

